### PR TITLE
fix(text): lyrics on the right sidebar visibility

### PR DESCRIPTION
**Pull request by SunsetTechuila**
image

### CODE REVIEW

**Comment by harbassan** [comment]
I think it would be better to keep the mask at the bottom atleast.

**Comment by SunsetTechuila** [comment]
it doesn't fit the original intention to mimic the console interface. Moreover, if you pay attention, there are no such smooth transitions anywhere at all

**Comment by harbassan** [comment]
I meant something more like this: 
image
making a clean mask at the bottom so that the final line isnt sitting on the border of the content box.

**Comment by SunsetTechuila** [comment]
idk how to make this so that it works with any text size

**Comment by harbassan** [comment]
This seems to work for the most part: 
`-webkit-mask-image: linear-gradient(180deg,black calc(100% - var(--font-size-lyrics)),transparent calc(100% - var(--font-size-lyrics)));` 
could also add a few pixels to it perhaps to get it absolutely perfect, but this works well as far as I tested.

**Comment by SunsetTechuila** [comment]
image
doesn't seem to work perfectly for me

**Review by harbassan — APPROVED** [review]

**Pull request merged**
