### PR TITLE
fix(THEMES): fix Sleek theme progress bar

### PR DESCRIPTION
**Pull request by ari-party**
Before: Spotify_CVtkvYxcMi

After: Spotify_10TFF4bleh

### CODE REVIEW

**Comment by ari-party** [comment]
(@harbassan)

**Comment by harbassan** [comment]
for the obfuscated class name selector that you removed, has it been replaced by another name, or has it just been removed completely. Because its not actually supposed to have the transition when manually setting the progress.

**Comment by ari-party** [comment]
> for the obfuscated class name selector that you removed, has it been replaced by another name, or has it just been removed completely. Because its not actually supposed to have the transition when manually setting the progress.

progress bar should not transition when manually moving it, correct?

**Comment by ari-party** [comment]
I've made the changes as requested.

notepad_ZNJeUERIw7

**Review by harbassan — APPROVED** [review]

**Pull request merged**
