### PR TITLE
[Dribbblish] Fix grid layout in global nav [StarryNight] Fix Root container glitch #1098

### PR DESCRIPTION
**Pull request by sanoojes**
Fixed grid layout in global nav and make it usable 

Preview:
Screenshot 2024-07-30 190258

This PR includes a fix for Starry Night that was unintentionally added. Since it's a small change and related to the other fixes, I'm keeping it here for now to streamline the process. In the future, I'll be more mindful of keeping unrelated changes on separate branches. Apologies for any confusion!

### CODE REVIEW

**Comment by sanoojes** [comment]
This PR includes a fix for Starry Night that was unintentionally added. Since it's a small change and related to the other fixes, I'm keeping it here for now to streamline the process. In the future, I'll be more mindful of keeping unrelated changes on separate branches. Apologies for any confusion!

**Comment by sanoojes** [comment]
Observed Behavior #1098: Top bar exhibits visual glitches, disappearing and reappearing.
Expected Behavior: Stable top bar display without flickering or disappearing.
Resolution: Remove unnecessary sidebar height calculation.

**Review by harbassan — APPROVED** [review]
For now it's fine but in the future could you make sure to maintain the code format of the original files so that we don't get hundreds of lines of style changes in the commits. Thanks for making the fixes though!

**Comment by sanoojes** [comment]
sure i will !

**Pull request merged**
