### PR TITLE
fix(Sleek): update theme

### PR DESCRIPTION
**Pull request by ajmeese7**
* fixes height of playbar when listening on a different device

### CODE REVIEW

**Comment by harbassan** [comment]
I honestly cant seem to understand why you're having the issue, but the existing code works for everyone else. Are you fully up to date with everything? Can you send a new screenshot of the issue where i can see all of the bottom.

**Comment by ajmeese7** [comment]
@harbassan I believe I am fully up to date on everything, my Spicetify is `v2.16.1` and my Spotify client is `1.1.84.716.gc5f8b819`. I have downloaded the latest version of the theme repository, followed the setup instructions, and ran `spicetify update`. My OS is `Zorin OS 16.2`.

This is what my Spotify looks like with the latest version of the pushed theme changes:

Problematic Spicetify UI

**Comment by harbassan** [comment]
Ah, I see the real issue now. For some reason your connect bar isn't visible, which is the thing thats supposed to push the whole bottom bar upwards. Do you have some sort of extension/snippet enabled that hides the connect bar?

**Comment by ajmeese7** [comment]
I guess I must have been, none of my extensions seemed like they were having an effect, but when I did a hard reset and wiped all marketplace content it was back to working all of a sudden!

Thanks for your help, closing this out now.

**Pull request closed without merging**
