### PR TITLE
feat(Ziro): rewrite

### LINKED ISSUE #639: [Ziro] Playback bar is misaligned when playing from remote device
Maybe a result of the new Spotify version, 1.1.74
image

### PR DESCRIPTION
**Pull request by schnensch0**
after taking a break for 5 months i have decided to completely rewrite ziro.

the big thing is the `@import`. i've set up github pages on my personal repo to import a separate file. this would allow me to skip creating a pull request here to update the theme.

also fixes #639 and #636

### CODE REVIEW

**Comment by CharlieS1103** [comment]
One potential issue I see with this method is that when people want to contribute to ziro, they will need to track down your personal repo.

**Comment by afonsojramos** [comment]
@schnensch0 to avoid this I've given you permissions to skip the reviews on PRs. Use it wisely! 😅 Can you test that it works?

**Comment by schnensch0** [comment]
doesn't look like it's working

**Comment by afonsojramos** [comment]
@schnensch0 Try again 😅

**Comment by schnensch0** [comment]
works now

**Comment by cdtinen** [comment]
Good job! Looks great and no issues 😄

**Pull request merged**
