### PR TITLE
Added Moonlight theme

### PR DESCRIPTION
**Pull request by Abod1960**
[➕ theme addition](https://github.com/spicetify/spicetify-themes/labels/%E2%9E%95%20theme%20addition)

@moonlight-theme is a dark color theme inspired by the camping vibe 🏕

This theme is as simple as possible with some tiny changes to the UI to keep your Spotify as you know it with some minor enhancements to have Spotify added to your moonlight setup...

**previews:**

dark_album
dark_playlist
dark_podcast
dark_profile
dark_search
dark_home

### CODE REVIEW

**Review by kyrie25 — CHANGES_REQUESTED** [review]
As a theme addition, we only need to store only the essential files (`user.css`, `color.ini`, Readme & assets), thus it'd be great if you can push those only.
Overall, splendid work! :) Thanks a lot for the effort.

**Comment by kyrie25** [comment]
Do update the Readme file on the repository's root repo so users can see your work being displayed also.

**Comment by Abod1960** [comment]
done 🎉
 
> Do update the Readme file on the repository's root folder so users can see your work being displayed also.

**Review by Overrevvv — APPROVED** [review]

**Review by harbassan — APPROVED** [review]

**Comment by Abod1960** [comment]
👋
anything I'm required to do...

**Comment by harbassan** [comment]
nope, just waiting for @kyrie25 to approve the pr.

**Comment by kyrie25** [comment]
> nope, just waiting for @kyrie25 to approve the pr.

I can only prepare so much, I'm not authorized to merge the theme addition to the repository.
It's up to the project manager on the decision.

**Comment by harbassan** [comment]
you requested changes tho, unless you review it and approve then we can't merge

**Comment by harbassan** [comment]
@Abod1960 i'm going to close this due to it being stale. If you open a new PR i'll be able to merge it. However, because of the new spotify update of YLX, which has become the new 'standard' layout, you're gonna need to update it so that it works with it, otherwise it's just going to end up as another broken theme on here. Thanks.

**Comment by Abod1960** [comment]
> @Abod1960 i'm going to close this due to it being stale. If you open a new PR i'll be able to merge it. However, because of the new spotify update of YLX, which has become the new 'standard' layout, you're gonna need to update it so that it works with it, otherwise it's just going to end up as another broken theme on here. Thanks.

pretty understandable, I'll do my best to update the theme and open a new PR asap...

**Pull request closed without merging**
