### PR TITLE
feat(Sleek): Adds Eldritch scheme

### PR DESCRIPTION
**Pull request by jacobrreed**
Adds the Eldritch scheme to Sleek theme 😄 
https://github.com/eldritch-theme/eldritch

### CODE REVIEW

**Comment by jacobrreed** [comment]
@harbassan This github action seems to be failing? anything I can do? it looks like it was going to assign it to you based on the actions logs

**Comment by obvRedwolf** [comment]
might add this theme to dribbblish if i have time, nice theme you made!

**Review by harbassan — APPROVED** [review]

**Comment by harbassan** [comment]
nice scheme!

**Comment by jacobrreed** [comment]
> might add this theme to dribbblish if i have time, nice theme you made!

if you do feel free to add the instructions to my repo https://github.com/eldritch-theme/spicetify

**Pull request merged**
