### PR TITLE
Add credits

### PR DESCRIPTION
**Pull request by CharlieS1103**

### CODE REVIEW

**Comment by afonsojramos** [comment]
Do you feel like this is necessary?

**Comment by CharlieS1103** [comment]
@afonsojramos I mean true, i just did it for marketplace in case I want to add it to my resume or something lol.

**Comment by afonsojramos** [comment]
Well, you can do that without your name there, you can just look at the contributions 😅

**Comment by CharlieS1103** [comment]
Did not know that lol

**Pull request closed without merging**
