### PR TITLE
feat(Matte): add Matte theme

### PR DESCRIPTION
**Pull request by darkthemer**

### CODE REVIEW

**Comment by kyrie25** [comment]
@afonsojramos Do we wish to add this after mono-repo like #582?

**Comment by afonsojramos** [comment]
Yeah, I'd say so! Let's sync up on the status of marketplace and support for the mono and maybe by the end of the month we can move to it

**Comment by darkthemer** [comment]
Would it be better if I made a separate repo instead of putting the theme in spicetify-themes?

**Comment by kyrie25** [comment]
> Would it be better if I made a separate repo instead of putting the theme in spicetify-themes?

Feel free to maintain the theme individually, but we welcome theme additions after the facilitations are done. If you still wish to have the theme stored here and maintained my the whole team then you can leave this PR open :)

**Review by harbassan — APPROVED** [review]

**Pull request merged**
