### PR TITLE
feat(Dribbblish): add rose pine color scheme

### PR DESCRIPTION
**Pull request by the-argus**
Not as fully complete as #716 because I couldn't for the life of me figure out how to get a preview image as good as the other ones that are in this repo. Also, I didn't include rose pine dawn or moon, as I don't use those and someone who does should probably be the one to make that colorscheme.

Oh also: linked to #783

### CODE REVIEW

**Comment by kyrie25** [comment]
It is recommended that you link a preview of your color scheme onto the Readme, and you shouldn't have any trouble doing so with the latest version of Spotify/Spicetify (1.1.90/2.11.1). Looking into your screenshot, are you perhaps using an outdated Spotify/Spicetify version?

**Comment by kyrie25** [comment]
You can use this screenshot I took as I tried to reconstruct yours:

Spotify_BPQZYPOQs5

**Comment by the-argus** [comment]
Thanks so much! My Dribbblish has always been a little jank... it's probably best that someone else took the screenshot anyways. I've added it to the dribbblish readme.

**Review by kyrie25 — APPROVED** [review]
Alright, LGTM! Thanks for your work. :)

**Comment by kyrie25** [comment]
> Thanks so much! My Dribbblish has always been a little jank... it's probably best that someone else took the screenshot anyways. I've added it to the dribbblish readme.

It's probably because a lot of classes on `1.1.84` was never mapped which explains why a lot of themes broke then. Are you using Linux by any chance?

**Comment by the-argus** [comment]
Yes, Arch linux was what that screenshot was taken on.

**Comment by kyrie25** [comment]
This is a gzip with the latest CSS map I bundled within for another Linux user that should fix most of the theme issues on `1.1.84`.
Replace your current Spicetify build with this, turn off your Internet connection (so that Spicetify would use the local CSS map) and then do `spicetify restore backup apply`, should do the trick as it worked for them.

[spicetify-2.9.9-linux-amd64.tar.gz](https://github.com/spicetify/spicetify-themes/files/9186380/spicetify-2.9.9-linux-amd64.tar.gz)

**Comment by nicoleajoy** [comment]
Hey, @the-argus! This looks good!

Apologies for going outside the scope of this repo. Just wanted to offer, if you're interested, please feel free to open a PR under the [Rose Pine Spotify repo](https://github.com/nicoleajoy/rose-pine-spotify) with your contributions there too!

**Pull request merged**
