### PR TITLE
feat(text): add forest green color scheme

### PR DESCRIPTION
**Pull request by CharlieS1103**

### CODE REVIEW

**Comment by harbassan** [comment]
earl? zeloopers? MIKE? beautiful.

**Comment by harbassan** [comment]
can you add the screesnhot to THEMES.md aswell

**Comment by CharlieS1103** [comment]
On it sir @harbassan, right after I finish this english project

**Comment by CharlieS1103** [comment]
@darkthemer Just letting you know this exists as I don't believe i'm able to assign the PR to you

**Review by harbassan — APPROVED** [review]

**Pull request merged**
