### PR TITLE
fix(BurntSienna): import fonts

### PR DESCRIPTION
**Pull request by kyrie25**
apparently everybody has been using Times New Roman as a fallback until now 💀

### CODE REVIEW

**Comment by CharlieS1103** [comment]
I like times new Roman

**Comment by kyrie25** [comment]
> I like times new Roman

Defo not the intention tho, there have been people getting stuff they didn't ask for.

**Review by CharlieS1103 — APPROVED** [review]
times new roman is still the best font but i digress

**Comment by pjaspinski** [comment]
Sorry, I was away and didn't have time to respond.
My idea was that users should install Montserrat font locally, but this fix makes it necessary only for people who use Spotify offline, so it's definitely an improvement.
Thanks for this pr @kyrie25 
Also, Times New Roman is a classic, I love it

**Pull request merged**
